# BackPropagation Using Keras For Regression

In [38]:
import numpy as np
import pandas as pd

In [39]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns= ['cpga','profile_score','lpa'])

In [40]:
df

,cpga,profile_score,lpa
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7


In [41]:
X = np.array(df.drop(columns = ['lpa']))
y =  df['lpa']

In [42]:
import tensorflow 
from tensorflow import keras 
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [43]:
model = Sequential()

model.add(Dense(2, activation = 'linear',input_dim = 2))
model.add(Dense(1, activation = 'linear'))

d:\DeepLearning.py\.venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [44]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_7 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [45]:
model.get_weights()

[array([[0.5503992 , 0.7304727 ],
        [0.22622883, 1.069856  ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 1.4017228],
        [-1.090462 ]], dtype=float32),
 array([0.], dtype=float32)]

In [46]:
new_weights = [np.array([[0.1,0.1],[0.1,0.1]],dtype = np.float32),np.array([0,0], dtype = np.float32),np.array([[0.1],[0.1]],dtype = np.float32),np.array([0],dtype = np.float32)]

In [47]:
model.set_weights(new_weights)

In [48]:
optimizer = keras.optimizers.Adam(learning_rate= 0.001)
model.compile(loss = 'mean_squared_error', optimizer = optimizer)

In [49]:
model.fit(df.iloc[:,0:-1].values, df['lpa'].values,epochs = 75, verbose = 1, batch_size= 1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: 27.8838
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 27.5797
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 27.2512
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 26.9212
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 26.5642 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 26.2066 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 25.8363 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 25.4361 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 46ms/step - loss: 25.0806 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 24.6528 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 45ms/step - loss: 24.2205 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 23.8054
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 23.4003 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 22.9306
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 22.4796
Epoch 16/75

In [50]:
model.get_weights()

[array([[0.37341636, 0.37341636],
        [0.36546263, 0.36546263]], dtype=float32),
 array([0.27214193, 0.27214193], dtype=float32),
 array([[0.37274337],
        [0.37274337]], dtype=float32),
 array([0.20466022], dtype=float32)]

# BackPropagation Using Keras For Classification

In [51]:
model2 = Sequential()

model2.add(Dense(2,activation = 'sigmoid', input_dim =2))
model2.add(Dense(1,activation='sigmoid'))

In [52]:
df = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]], columns=['cgpa', 'profile_score', 'placed'])

In [53]:
model2.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_9 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [54]:
model2.get_weights()

[array([[-0.64229184,  0.6225841 ],
        [-1.1428573 , -0.84860754]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 0.2221533],
        [-1.1058459]], dtype=float32),
 array([0.], dtype=float32)]

In [55]:
new_weights = [np.array([[0.1,0.1],[0.1,0.1]],dtype = np.float32),np.array([0,0],dtype = np.float32),np.array([[0.1],[0.1]], dtype = np.float32), np.array([0], dtype = np.float32)]

In [56]:
model2.set_weights(new_weights)

In [57]:
optimizer = keras.optimizers.Adam(learning_rate= 0.001)
model2.compile(loss = 'binary_crossentropy', optimizer = optimizer)


In [58]:
model2.fit(df.drop(columns = ['placed']).values, df['placed'].values, epochs = 75, verbose = 1, batch_size= 1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.6943
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.6942
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.6940
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.6938
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.6939
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.6939 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.6938
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.6937 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.6940
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.6939 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.6938 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.6936
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 0.6936 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.6936
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.6936
Epoch 16/75
4/4 ━━━━━━━━━━━━━